const newAd: AdCampaign = {
  id: generateUUID(),
  professorId: currentUser.id,
  professorName: `${currentUser.firstName || ''} ${currentUser.lastName || ''}`.trim(),
  name: title,
  title,
  description,
  targetAudience,
  minAge,
  maxAge,
  budget: calculatedTotalBudget,
  bidStrategy: 'CPM' as const,
  bidAmount: 0.5,
  isActive: true,
  imageUrl,
  linkUrl: linkUrl || '#',
  ctaText,
  timestamp: Date.now(),
  locations: locations
};